dashboard/urls.py
from django.urls import path
from .import views


app_name = 'dashboard'

urlpatterns = [
    path('welcome/',views.dashboard,name='dashboard'),
    path('employees/all/',views.dashboard_employees,name='employees'),
    path('employee/create/',views.dashboard_employees_create,name='employeecreate'),
    path('employee/profile/<int:id>/',views.dashboard_employee_info,name='employeeinfo'),
    path('employee/profile/edit/<int:id>/',views.employee_edit_data,name='edit'),

    path('leave/apply/',views.leave_creation,name='createleave'),
    path('leaves/pending/all/',views.leaves_list,name='leaveslist'),
    path('leaves/approved/all/',views.leaves_approved_list,name='approvedleaveslist'),
    path('leaves/cancel/all/',views.cancel_leaves_list,name='canceleaveslist'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview'),
    path('leaves/view/table/',views.view_my_leave_table,name='staffleavetable'),
    path('leave/approve/<int:id>/',views.approve_leave,name='userleaveapprove'),
    path('leave/unapprove/<int:id>/',views.unapprove_leave,name='userleaveunapprove'),
    path('leave/cancel/<int:id>/',views.cancel_leave,name='userleavecancel'),
    path('leave/uncancel/<int:id>/',views.uncancel_leave,name='userleaveuncancel'),
    path('leaves/rejected/all/',views.leave_rejected_list,name='leavesrejected'),
    path('leave/reject/<int:id>/',views.reject_leave,name='reject'),
    path('leave/unreject/<int:id>/',views.unreject_leave,name='unreject'),
  
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include("user.urls")),
    path('',views.index_view,name='home'),
    path('dashboard/',include("dashboard.urls")),
]

user/urls.py
from django.urls import path
from .import views

app_name ='user'

urlpatterns = [

    path('user_create/',views.register_user,name = 'register'),
    path('user_login/',views.login_view,name = 'login'),
    path('users/all',views.users_list,name='users'),
    path('logout/',views.logout_view,name='logout'),
]

templates/_layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>hiii</title>
</head>

<body>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="center-me-please ">
            <li>
                <a href="{% url 'dashboard:dashboard' %} ">Dashboard</a>
            </li>
            <li class="">
                <a href="/">
                    <i class="pe-7s-home"></i>
                    <p>Home</p>
                </a>
            </li>
            {% if request.user.is_superuser and request.user.is_staff %}
            <li>
                <a href="{% url 'dashboard:employees' %}">
                    <i class="pe-7s-users"></i>
                    <p>Employee</p>
                </a>
            </li>
            {% endif %}
            <li>
                {% if request.user.is_superuser %}<a href="{% url 'dashboard:leaveslist' %}">{% else %}<a href="{% url 'dashboard:staffleavetable' %}"> {% endif %}
                    <i class="pe-7s-news-paper"></i>
                    <p>Leave</p>
                </a>
            </li>
        </ul>
</body>

</html>

templates/index.html
<!doctype html>

<html lang="en">

<head>
</head>

<body>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="center-me-please ">
            <li><a href="{% url 'user:login' %} ">Login</a></li>
        </ul>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="center-me-please ">
            <li>
                <a href="{% url 'user:register' %} ">Account create</a>
            </li>
        </ul>
    </div>
</body>

</html>