dashboard/urls.py
from django.urls import path
from .import views


app_name = 'dashboard'

urlpatterns = [
    path('welcome/',views.dashboard,name='dashboard'),
    path('employees/all/',views.dashboard_employees,name='employees'),
    path('employee/create/',views.dashboard_employees_create,name='employeecreate'),
    path('employee/profile/<int:id>/',views.dashboard_employee_info,name='employeeinfo'),
    path('employee/profile/edit/<int:id>/',views.employee_edit_data,name='edit'),

    path('leave/apply/',views.leave_creation,name='createleave'),
    path('leaves/pending/all/',views.leaves_list,name='leaveslist'),
    path('leaves/approved/all/',views.leaves_approved_list,name='approvedleaveslist'),
    path('leaves/cancel/all/',views.cancel_leaves_list,name='canceleaveslist'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview'),
    path('leaves/view/table/',views.view_my_leave_table,name='staffleavetable'),
    path('leave/approve/<int:id>/',views.approve_leave,name='userleaveapprove'),
    path('leave/unapprove/<int:id>/',views.unapprove_leave,name='userleaveunapprove'),
    path('leave/cancel/<int:id>/',views.cancel_leave,name='userleavecancel'),
    path('leave/uncancel/<int:id>/',views.uncancel_leave,name='userleaveuncancel'),
    path('leaves/rejected/all/',views.leave_rejected_list,name='leavesrejected'),
    path('leave/reject/<int:id>/',views.reject_leave,name='reject'),
    path('leave/unreject/<int:id>/',views.unreject_leave,name='unreject'),
  
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include("user.urls")),
    path('',views.index_view,name='home'),
    path('dashboard/',include("dashboard.urls")),
]

user/urls.py
from django.urls import path
from .import views

app_name ='user'

urlpatterns = [

    path('user_create/',views.register_user,name = 'register'),
    path('user_login/',views.login_view,name = 'login'),
    path('users/all',views.users_list,name='users'),
    path('logout/',views.logout_view,name='logout'),
]

dashboard/models.py
from django.db import models
from emp.utility import code_format
from emp.managers import EmployeeManager
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
# Create your models here.

class Department(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = ('department')
        ordering = ['name']

    def __str__(self):
        return self.name
    
class Employee(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    department = models.ForeignKey(Department,verbose_name =_('department'),on_delete=models.CASCADE)
    address = models.CharField(max_length=50)
    contactnum = models.IntegerField()
    email = models.EmailField(max_length=30, null=True)
    employeeid = models.CharField(_('Employee Id Number'),max_length=5,null=True,blank=True)
    
    objects = EmployeeManager()
    class Meta:
        verbose_name = ('Employee')

    def __str__(self):
        return self.get_full_name

    @property
    def get_full_name(self):
        fullname = ''
        firstname = self.firstname
        lastname = self.lastname
        if (firstname and lastname):
            fullname = firstname + ' ' + lastname
        return fullname

    def save(self, *args, **kwargs):

        get_id = self.employeeid
        data = code_format(get_id)
        self.employeeid = data
        super().save(*args, **kwargs)
        # print(self.employeeid)
        
    @property
    def can_apply_leave(self):
        pass

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib import messages
from emp.forms import EmployeeCreateForm
from leave.models import Leave
from emp.models import *
from leave.forms import LeaveCreationForm


def dashboard(request):

    dataset = dict()
    user = request.user

    if not request.user.is_authenticated:
        return redirect('user:login')

    employees = Employee.objects.all()
    leaves = Leave.objects.all_pending_leaves()

    staff_leaves = Leave.objects.filter(user=user)

    dataset['employees'] = employees
    dataset['leaves'] = leaves

    dataset['staff_leaves'] = staff_leaves

    return render(request, 'dashboard/dashboard_index.html', dataset)


def dashboard_employees(request):
    if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
        return redirect('/')

    dataset = dict()
    departments = Department.objects.all()
    employees = Employee.objects.all()
    query = request.GET.get('search')
    if query:
        employees = employees.filter(
            Q(firstname__icontains=query) |
            Q(lastname__icontains=query)
        )
    return render(request, 'dashboard/employee_app.html', dataset)


def dashboard_employees_create(request):
    if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
        return redirect('/')

    if request.method == 'POST':
        print("asdasdasdasdas")
        form = EmployeeCreateForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            
            user = request.POST.get('user')
            assigned_user = User.objects.get(id=user)
            instance.user = assigned_user
            instance.firstname = request.POST.get('firstname')
            instance.lastname = request.POST.get('lastname')
            department = Department.objects.get(id=request.POST.get('department'))
            instance.department = department
            instance.address = request.POST.get('address')
            instance.contactnum = request.POST.get('contactnum')
            instance.email = request.POST.get('email')
            instance.employeeid = request.POST.get('employeeid')
            instance.save()
            return redirect('dashboard:employees')
        else:
            messages.error(request, 'Trying')
            return redirect('/')

    dataset = dict()
    form = EmployeeCreateForm()
    dataset['form'] = form
    dataset['title'] = 'register employee'
    return render(request, 'dashboard/employee_create.html', dataset)


def employee_edit_data(request, id):
    if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
        return redirect('/')
    employee = get_object_or_404(Employee, id=id)
    if request.method == 'POST':
        form = EmployeeCreateForm(
            request.POST or None, request.FILES or None, instance=employee)
        if form.is_valid():
            instance = form.save(commit=False)

            user = request.POST.get('user')
            assigned_user = User.objects.get(id=user)

            instance.user = assigned_user
            instance.firstname = request.POST.get('firstname')
            instance.lastname = request.POST.get('lastname')
            department = Department.objects.get()
            instance.department = department
            instance.address = request.POST.get('address')
            instance.contactnum = request.POST.get('contactnum')
            instance.email = request.POST.get('email')
            instance.employeeid = request.POST.get('employeeid')

            instance.save()
            messages.success(request, 'Account Updated Successfully !!!')
            return redirect('dashboard:employees')
        else:

            messages.error(request, 'Error Updating account')
            return HttpResponse("Form data not valid")
    dataset = dict()
    form = EmployeeCreateForm(request.POST or None,
                              request.FILES or None, instance=employee)
    dataset['form'] = form
    dataset['title'] = 'edit - {0}'.format(employee.get_full_name)
    return render(request, 'dashboard/employee_create.html', dataset)


def dashboard_employee_info(request, id):
    if not request.user.is_authenticated:
        return redirect('/')

    employee = get_object_or_404(Employee, id=id)

    dataset = dict()
    dataset['employee'] = employee
    dataset['title'] = 'profile - {0}'.format(employee.get_full_name)
    return render(request, 'dashboard/employee_detail.html', dataset)


# ---------------------LEAVE-------------------------------------------


def leave_creation(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    if request.method == 'POST':
        form = LeaveCreationForm(data=request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            user = request.user
            instance.user = user
            instance.save()

            # print(instance.defaultdays)
            messages.success(request, 'Leave Request Sent,wait for codezilla Managers response',
                             extra_tags='alert alert-success alert-dismissible show')
            return redirect('dashboard:createleave')

        messages.error(request, 'failed to Request a Leave,please check entry dates',
                       extra_tags='alert alert-warning alert-dismissible show')
        return redirect('dashboard:createleave')

    dataset = dict()
    form = LeaveCreationForm()
    dataset['form'] = form
    dataset['title'] = 'Apply for Leave'
    return render(request, 'dashboard/create_leave.html', dataset)


def leaves_list(request):
    if not (request.user.is_staff and request.user.is_superuser):
        return redirect('/')
    leaves = Leave.objects.all_pending_leaves()
    return render(request, 'dashboard/leaves_recent.html', {'leave_list': leaves, 'title': 'leaves list - pending'})


def leaves_approved_list(request):
    if not (request.user.is_superuser and request.user.is_staff):
        return redirect('/')
    # approved leaves -> calling model manager method
    leaves = Leave.objects.all_approved_leaves()
    return render(request, 'dashboard/leaves_approved.html', {'leave_list': leaves, 'title': 'approved leave list'})


def leaves_view(request, id):
    if not (request.user.is_authenticated):
        return redirect('/')

    leave = get_object_or_404(Leave, id=id)
    print(leave.user)
    employee = Employee.objects.all()
    print(employee)
    return render(request, 'dashboard/leave_detail_view.html', {'leave': leave, 'employee': employee, 'title': '{0}-{1} leave'.format(leave.user.username, leave.status)})


def approve_leave(request, id):
    if not (request.user.is_superuser and request.user.is_authenticated):
        return redirect('/')
    leave = get_object_or_404(Leave, id=id)
    user = leave.user
    employee = Employee.objects.filter(user=user)[0]
    leave.approve_leave

    messages.error(request, 'Leave successfully approved for {0}'.format(
        employee.get_full_name), extra_tags='alert alert-success alert-dismissible show')
    return redirect('dashboard:userleaveview', id=id)


def cancel_leaves_list(request):
    if not (request.user.is_superuser and request.user.is_authenticated):
        return redirect('/')
    leaves = Leave.objects.all_cancel_leaves()
    return render(request, 'dashboard/leaves_cancel.html', {'leave_list_cancel': leaves, 'title': 'Cancel leave list'})


def unapprove_leave(request, id):
    if not (request.user.is_authenticated and request.user.is_superuser):
        return redirect('/')
    leave = get_object_or_404(Leave, id=id)
    leave.unapprove_leave
    return redirect('dashboard:leaveslist')  # redirect to unapproved list


def cancel_leave(request, id):
    if not (request.user.is_superuser and request.user.is_authenticated):
        return redirect('/')
    leave = get_object_or_404(Leave, id=id)
    leave.leaves_cancel

    messages.success(request, 'Leave is canceled',
                     extra_tags='alert alert-success alert-dismissible show')
    # work on redirecting to instance leave - detail view
    return redirect('dashboard:canceleaveslist')


def uncancel_leave(request, id):
    if not (request.user.is_superuser and request.user.is_authenticated):
        return redirect('/')
    leave = get_object_or_404(Leave, id=id)
    leave.status = 'pending'
    leave.is_approved = False
    leave.save()
    messages.success(request, 'Leave is uncanceled,now in pending list',
                     extra_tags='alert alert-success alert-dismissible show')
    # work on redirecting to instance leave - detail view
    return redirect('dashboard:canceleaveslist')


def leave_rejected_list(request):

    dataset = dict()
    leave = Leave.objects.all_rejected_leaves()

    dataset['leave_list_rejected'] = leave
    return render(request, 'dashboard/rejected_leaves_list.html', dataset)


def reject_leave(request, id):
    dataset = dict()
    leave = get_object_or_404(Leave, id=id)
    leave.reject_leave
    messages.success(request, 'Leave is rejected',
                     extra_tags='alert alert-success alert-dismissible show')
    return redirect('dashboard:leavesrejected')

    # return HttpResponse(id)


def unreject_leave(request, id):
    leave = get_object_or_404(Leave, id=id)
    leave.status = 'pending'
    leave.is_approved = False
    leave.save()
    messages.success(request, 'Leave is now in pending list ',
                     extra_tags='alert alert-success alert-dismissible show')

    return redirect('dashboard:leavesrejected')


def view_my_leave_table(request):

    if request.user.is_authenticated:
        user = request.user

templates/dashboard/create_leave.html
{% block content %}
<section class="content">
    <section class="container-fluid">

        <section class="form-wrapper">
            <section class="row">
                <section class="col col-lg-12 col-md-12  col-sm-12">

                    {% if messages %} {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags}}" {% endif %}>
                        {{ message }}
                        <button type="button" class="close" id="override-start" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                    {% endfor %} {% endif %}

                </section>
            </section>

            <section class="row">
                <section class="col-lg-12 col-md-12 col-sm-12 text-center space-margin">
                    <h3 class="title-h3">{{ title}}</h3>
                </section>
            </section>

            <section class="row">
                <section class="col-lg-12 col-md-12 col-sm-12">
                    <form action="{% url 'dashboard:createleave' %}" method="POST">
                        {% csrf_token %} {{ form}}
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Send Request</button>
                    </form>
                </section>

            </section>

        </section>

    </section>
</section>
{% endblock %}

templates/dashboard/employee_detail.html
{% block content %}
<section class="content">
    <section class="container-fluid">
        <section class="row">
            <section class="col col-lg-12 col-md-12  col-sm-12">
                {% if messages %} {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags}}" {% endif %}>
                    {{ message }}
                    <button type="button" class="close" id="override-start" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                </div>
                {% endfor %} {% endif %}

            </section>
        </section>
        <section class="row">
            <section class="text-center">
                <h3><span class="employee-name-title">{{ employee.get_full_name}}</span></h3>
            </section>
        </section>

        <section class="row">
            <section class="col col-lg-4 col-md-4 col-sm-12 profile-wrapper">
                <section class="text-centered" style="margin-top: 3px;">

                    <ul class="list-group">
                        <li class="list-group-item"><span>Fullname</span>
                            <div>{{ employee.get_full_name }}</div>
                        </li>
                        {% if employee.email %}
                        <li class="list-group-item"><span>Email</span>
                            <div>{{ employee.email}}</div>
                        </li>
                        {% endif %}
                        <li class="list-group-item"><span>Department</span>
                            <div>{{ employee.department}}</div>
                        </li>
                        <li class="list-group-item"><span>contact no</span>
                            <div>{{ employee.contactnum}}</div>
                        </li>
                        <li class="list-group-item"><span>address</span>
                            <div>{{ employee.address}}</div>
                        </li>

                        {% if employee.is_blocked %}
                        <li class="list-group-item"><span>Status</span>
                            <div>Inactive</div>
                        </li>
                        {% else %}
                        <li class="list-group-item"><span>Status</span>
                            <div> active</div>
                        </li>
                        {% endif %}
                        <div>
                            <span style="font-style: italic;">updated - {{employee.updated}}</span>
                        </div>

                    </ul>
                </section>
            </section>
            <section class="col col-lg-8">
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingOne">
                            <h4 class="panel-title">
                                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                PERSONAL INFORMATIONS 
                              </a>
                            </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                            <div class="panel-body">
                                <div class="container-fluid">
                                    <div class="row">
                                        <div class="col col-lg-6">

                                            {% if employee %}

                                            <div class="list-group" id="list-tab" role="tablist">
                                                <!-- <a class="list-group-item list-group-item-action" id="list-home-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Salutation</span> <div>{{ employee.title }}</div> -->
                                                </a> {% if employee.firstname %}
                                                <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Firstname</span> <div> {{ employee.firstname}} </div>
                                            </a> {% endif %} {% if employee.lastname %}
                                                <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Lastname</span> <div> {{ employee.lastname }} </div>
                                            </a> {% endif %} {% if employee.othername %}
                                                <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Othername</span> <div>{{ employee.othername}} </div>
                                            </div>
                                            </a> {% endif %} {% if employee.email %}
                                                <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Email </span><div>{{ employee.email }} </div>
                                            </a> {% endif %} {% if employee.contact %}
                                                <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Contact</span> <div> {{ employee.contact }}</div></a> {% endif %} {%
                                                if employee.contact%}
                                                <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Employee ID</span> <div>{{ employee.employeeid }}</div></a> {% endif
                                                %} {% if employee.address %}
                                                <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Address</span> <div>{{ employee.address }}</div></a> {% endif %} {%
                                                if request.user.is_superuser %}
                                                <div>
                                                    <span><a href="{% url 'dashboard:edit' employee.id %}">Edit</a></span>
                                                </div>

                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </section>
    </section>
</section>

{% endblock %}

templates/dashboard/leave_detail_view.html
{% block content %}
<section class="content">
    <section class="container-fluid">

        <section class="form-wrapper">
            <section class="row">
                <section class="col col-lg-8 col-md-12  col-sm-12">

                    {% if messages %} {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags}}" {% endif %}>
                        {{ message }}
                        <button type="button" class="close" id="override-start" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                    </div>
                    {% endfor %} {% endif %}

                </section>
            </section>

            <section class="row">
                <section class="col-lg-12 col-md-12 col-sm-12 text-center space-margin">
                    <h3 class="title-h3">{{ employee.get_full_name }}</h3>
                </section>
            </section>

            <section class="row">
                <section class="col-lg-8 col-md-12 col-sm-12">
                    <div class="list-group" id="list-tab" role="tablist">
                        <a class="list-group-item list-group-item-action" id="list-home-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Employee</span> <div>{{ employee.get_full_name }}</div>
                                            </a>
                        <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Start Date</span> <div> Start Date {{ leave.startdate }}</div>
                                            </a>
                        <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="" role="tab" aria-controls=""><span>End Date</span><div>{{ leave.enddate}}</div>
                                            </a>
                        <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Duration</span> <div>{{ leave.leave_days}}</div>
                                            </a>
                        <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Type</span> <div>{{ leave.leavetype}}</div>
                                            </a>
                        <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Reason</span> <div>{{ leave.reason}}</div>
                                            </a>
                        <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Status</span> <div>{{ leave.status}}</div>
                                             </a>


                    </div>

                </section>
            </section>



            <span style="font-size: 13px;padding-left: 1rem;" class="pull-left">Created {{ leave.created }}</span> {% if request.user.is_superuser and request.user.is_staff %}

            <section class="row">
                <section class="col col-lg-4 col-sm-12 col-lg-offset-7 text-center">
                    <div class="btn-group btn-group-justified">
                        {%if leave.leave_approved %}
                        <a href="{% url 'dashboard:userleaveunapprove' leave.id %}" class="btn btn-primary" name='unapprove'>UNAPPROVE
                          </a> {% else %}
                        <a href="{% url 'dashboard:userleaveapprove' leave.id %}" class="btn btn-primary" name='approve'>APPROVE
                          </a> {% endif %}
                        <a href="{% url 'dashboard:userleavecancel' leave.id %}" class="btn btn-info" name='cancel'>CANCEL</a>
                        <a href="{% url 'dashboard:reject' leave.id %}" class="btn btn-warning" name='reject'>REJECT</a>
                    </div>
                </section>
            </section>

            {% endif %}

        </section>

    </section>
    <!-- /container -->
</section>
{% endblock %}

templates/dashboard/leaves_approved.html
{% block content %}
<section class="content">
    <section class="container-fluid">
        <section class="row">
            <section class="col col-sm-8 offset-sm-2">

                {% if messages %} {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags}}" {% endif %}>
                    {{ message }}
                    <button type="button" class="close" id="override-start" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                </div>
                {% endfor %} {% endif %}

            </section>
        </section>

        <!-- TABLE -->
        <div class="table-responsive table-shadow">
            <div class="text-center table-description">
                <h4 class="title-h3" style="color: #60a0b3 !important;
    						text-shadow: 1px 0px rgba(0,0,0,0.11)">APPROVED LEAVES</h4>
            </div>
            <section class="total-leaves-count">
                {% if leave_list %}
                <p>Total approved leaves - <span>{{ leave_list.count }}</span></p>
                {% endif %}
            </section>

            <table class="table">
                <thead>
                    <tr>
                        <!-- <th scope="col">#</th> -->
                        <th scope="col">User</th>
                        <th scope="col">Type</th>
                        <th scope="col">Day(s)</th>
                        <th scope="col">Status</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for leave in leave_list %}
                    <tr>

                        <td>{{ leave.user }}</td>
                        <td>{{ leave.leavetype}}</td>
                        <td>{{ leave.leave_days }}</td>
                        <td>{{ leave.status }}</td>

                        <td>
                            <a href="{% url 'dashboard:userleaveview' leave.id %}">
                                <span>view</span>
                            </a>

                            <a href="{% url 'dashboard:userleaveunapprove' leave.id %}">
                                <span>unapprove</span>
                            </a>

                        </td>
                    </tr>

                    {% endfor %}

                </tbody>

            </table>

        </div>
        <!-- /TABLE -->

    </section>
    <!-- /container -->


</section>
{% endblock %}

templates/dashboard/leaves_cancel.html
{% block content %}
<section class="content">
    <section class="container-fluid">
        <section class="row">
            <section class="col col-sm-8 offset-sm-2">

                {% if messages %} {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags}}" {% endif %}>
                    {{ message }}
                    <button type="button" class="close" id="override-start" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                </div>
                {% endfor %} {% endif %}

            </section>
        </section>

        <!-- TABLE -->
        <div class="table-responsive table-shadow">
            <div class="text-center table-description">
                <h4 class="title-h3" style="color: #60a0b3 !important;
    						text-shadow: 1px 0px rgba(0,0,0,0.11)">CANCELLED LEAVES</h4>
            </div>

            <section class="total-leaves-count">
                {% if leave_list_cancel %}
                <p>Total cancelled leaves - <span>{{ leave_list_cancel.count }}</span></p>
                {% endif %}
            </section>

            <table class="table">
                <thead>
                    <tr>
                        <!-- <th scope="col">#</th> -->
                        <th scope="col">User</th>
                        <th scope="col">Type</th>
                        <th scope="col">Day(s)</th>
                        <th scope="col">Status</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for leave in leave_list_cancel %}
                    <tr>

                        <td>{{ leave.user }}</td>
                        <td>{{ leave.leavetype}}</td>
                        <td>{{ leave.leave_days }}</td>
                        <td>{{ leave.status }}</td>

                        <td>
                            <a href="{% url 'dashboard:userleaveview' leave.id %}">
                                <span>view</span>
                            </a>

                            {% if not leave.is_approved %}
                            <a href="{% url 'dashboard:userleaveuncancel' leave.id %}">uncancel</a> {% endif %}

                        </td>
                    </tr>

                    {% endfor %}

                </tbody>

            </table>

        </div>
        <!-- /TABLE -->

    </section>
    <!-- /container -->


</section>
{% endblock %}